services:
  fnd-server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.development
    ports:
      - "8060:8060/tcp"
    volumes:
      - ./packages/fnd-server/src:/app/packages/fnd-server/src
