version: "3"

services:
  redis:
    restart: always
    image: redis:6-alpine
    env_file:
      - ./.env.development
    ports:
      - "6379:6379"
  fnd-server:
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.development
    ports:
      - "8060:8060/tcp"
    volumes:
      - .:/app
    command: "/app/ci.sh"
