import type { TORUS_LEGACY_NETWORK_TYPE } from "./interfaces";

export const TORUS_LEGACY_NETWORK = {
  LEGACY_MAINNET: "mainnet",
  LEGACY_TESTNET: "testnet",
  LEGACY_CYAN: "cyan",
  LEGACY_AQUA: "aqua",
  LEGACY_CELESTE: "celeste",
} as const;

export const TORUS_SAPPHIRE_NETWORK = {
  SAPPHIRE_DEVNET: "sapphire_devnet",
  SAPPHIRE_TESTNET: "sapphire_testnet",
  SAPPHIRE_MAINNET: "sapphire_mainnet",
  ...TORUS_LEGACY_NETWORK,
} as const;

export const TORUS_NETWORK = {
  ...TORUS_SAPPHIRE_NETWORK,
} as const;

export const PROXY_CONTRACT_ADDRESS = {
  [TORUS_LEGACY_NETWORK.LEGACY_MAINNET]: "0xf20336e16B5182637f09821c27BDe29b0AFcfe80",

  [TORUS_LEGACY_NETWORK.LEGACY_TESTNET]: "0xd084604e5FA387FbC2Da8bAab07fDD6aDED4614A",

  [TORUS_LEGACY_NETWORK.LEGACY_CYAN]: "0x9f072ba19b3370e512aa1b4bfcdaf97283168005",

  [TORUS_LEGACY_NETWORK.LEGACY_AQUA]: "0x29Dea82a0509153b91040ee13cDBba0f03efb625",

  [TORUS_LEGACY_NETWORK.LEGACY_CELESTE]: "0x6Bffb4e89453069E7487f0fa5c9f4a2D771cce6c",
};

export const MULTI_CLUSTER_NETWORKS: TORUS_LEGACY_NETWORK_TYPE[] = [
  TORUS_LEGACY_NETWORK.LEGACY_AQUA,
  TORUS_LEGACY_NETWORK.LEGACY_CELESTE,
  TORUS_LEGACY_NETWORK.LEGACY_CYAN,
];

export const LEGACY_NETWORKS_ROUTE_MAP: Record<TORUS_LEGACY_NETWORK_TYPE, string> = {
  [TORUS_LEGACY_NETWORK.LEGACY_AQUA]: TORUS_LEGACY_NETWORK.LEGACY_AQUA,
  [TORUS_LEGACY_NETWORK.LEGACY_CELESTE]: TORUS_LEGACY_NETWORK.LEGACY_CELESTE,
  [TORUS_LEGACY_NETWORK.LEGACY_CYAN]: TORUS_LEGACY_NETWORK.LEGACY_CYAN,
  [TORUS_LEGACY_NETWORK.LEGACY_MAINNET]: TORUS_LEGACY_NETWORK.LEGACY_MAINNET,
  [TORUS_LEGACY_NETWORK.LEGACY_TESTNET]: "teal",
};

export const NETWORK_MAP = {
  [TORUS_LEGACY_NETWORK.LEGACY_MAINNET]: "mainnet",
  [TORUS_LEGACY_NETWORK.LEGACY_TESTNET]: "goerli",
  [TORUS_LEGACY_NETWORK.LEGACY_CYAN]: "polygon-mainnet",
  [TORUS_LEGACY_NETWORK.LEGACY_AQUA]: "polygon-mainnet",
  [TORUS_LEGACY_NETWORK.LEGACY_CELESTE]: "polygon-mainnet",
};

export const SIGNER_MAP = {
  [TORUS_LEGACY_NETWORK.LEGACY_MAINNET]: "https://signer.tor.us",
  [TORUS_LEGACY_NETWORK.LEGACY_TESTNET]: "https://signer.tor.us",
  [TORUS_LEGACY_NETWORK.LEGACY_CYAN]: "https://signer-polygon.tor.us",
  [TORUS_LEGACY_NETWORK.LEGACY_AQUA]: "https://signer-polygon.tor.us",
  [TORUS_LEGACY_NETWORK.LEGACY_CELESTE]: "https://signer-polygon.tor.us",
};
